version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: vechedb
      POSTGRES_USER: veche
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - local

networks:
  local:

volumes:
  pgdata: