services:
  postgres:
    build:
      context: ./infra/postgres
      dockerfile: Dockerfile.pg
      args:
        PG_MAJOR: 17
    container_name: postgres
    environment:
      POSTGRES_DB: vechedb
      POSTGRES_USER: veche
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    command: >
      postgres -c shared_preload_libraries=pg_cron
               -c cron.database_name=vechedb
    networks:
      - local

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - local

networks:
  local:

volumes:
  pgdata: