ARG PG_MAJOR=17
FROM postgres:${PG_MAJOR}-bookworm
RUN apt-get update && apt-get install -y wget gnupg && \
    echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg && \
    apt-get update && apt-get install -y postgresql-${PG_MAJOR}-cron && \
    rm -rf /var/lib/apt/lists/*