ALTER TABLE comments
    ADD content VARCHAR(4000);

ALTER TABLE comments
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE companies
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE discussion_votes
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE discussions
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE parties
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE sessions
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE comments
    DROP COLUMN subject;